<?php
/**
 * Title: Faq Accordion
 * Slug: accordion
 * Categories: faq
 */
?>
<!-- wp:group {"align":"full","style":{"spacing":{"padding":{"top":"var:preset|spacing|xxl","bottom":"var:preset|spacing|xxl"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull" style="padding-top:var(--wp--preset--spacing--xxl);padding-bottom:var(--wp--preset--spacing--xxl)"><!-- wp:columns {"align":"wide","style":{"spacing":{"blockGap":{"top":"var:preset|spacing|xxl","left":"var:preset|spacing|xxl"}}}} -->
<div class="wp-block-columns alignwide"><!-- wp:column {"width":"40%","style":{"position":{"desktop":"sticky"},"top":{"desktop":"2em"},"right":{"desktop":""},"bottom":{"desktop":""},"left":{"desktop":""}}} -->
<div class="wp-block-column" style="flex-basis:40%"><!-- wp:heading {"align":"wide","style":{"spacing":{"margin":{"top":"var:preset|spacing|xs"}}}} -->
<h2 class="wp-block-heading alignwide" style="margin-top:var(--wp--preset--spacing--xs)">Frequently asked questions about our services</h2>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"is-style-sub-heading"} -->
<p class="is-style-sub-heading">Have a different question? Contact our team now for a fast response.</p>
<!-- /wp:paragraph -->
<!-- wp:group {"style":{"spacing":{"padding":{"top":"var:preset|spacing|xxs","bottom":"0"},"blockGap":{"top":"var:preset|spacing|md","left":"var:preset|spacing|xs"}}},"className":"is-style-default","layout":{"type":"flex","flexWrap":"wrap"}} -->
<div class="wp-block-group is-style-default" style="padding-top:var(--wp--preset--spacing--xxs);padding-bottom:0"><!-- wp:buttons {"layout":{"type":"flex","justifyContent":"center","flexWrap":"wrap"},"style":{"position":{"all":"relative"},"border":{"radius":"60px"},"transformHover":"","transform":""}} -->
<div class="wp-block-buttons" style="border-radius:60px"><!-- wp:button {"backgroundColor":"primary-600","textColor":"neutral-0","style":{"spacing":{"padding":{"top":"6px","bottom":"6px","left":"var:preset|spacing|lg","right":"6px"},"blockGap":"var:preset|spacing|sm"},"transformHover":{"scale":""},"transformIcon":{"rotate":"45"},"filterHover":{"opacity":"90"},"filter":"","elements":{"link":{"color":{"text":"var:preset|color|neutral-0"}}}},"className":"is-style-fill hide-light-mode","size":"large","iconSet":"","iconSize":"","iconSvgString":""} -->
<div class="wp-block-button is-style-fill hide-light-mode has-transform" style="padding-top:6px;padding-right:6px;padding-bottom:6px;padding-left:var(--wp--preset--spacing--lg);--filter-hover:opacity(90%);--transform-icon-hover:rotate(45deg)"><a class="wp-block-button__link has-neutral-0-color has-primary-600-background-color has-text-color has-background has-link-color wp-element-button" style="padding-top:6px;padding-right:6px;padding-bottom:6px;padding-left:var(--wp--preset--spacing--lg)">Contact us<img class="wp-image-2249" style="width: 54px;" src="<?php echo esc_url( content_url( "/themes/agencify/assets/" ) ) ?>svg/arrow-up-right.svg" alt=""></a></div>
<!-- /wp:button -->
<!-- wp:button {"backgroundColor":"neutral-950","textColor":"primary-400","style":{"spacing":{"padding":{"top":"6px","bottom":"6px","left":"var:preset|spacing|lg","right":"6px"},"blockGap":"var:preset|spacing|sm"},"elements":{"link":{"color":{"text":"var:preset|color|primary-400"}}},"transformHover":{"scale":""},"transformIcon":{"rotate":"45"},"filterHover":{"brightness":"110"}},"className":"is-style-fill hide-dark-mode","size":"large","iconSet":"","iconSize":"","iconSvgString":""} -->
<div class="wp-block-button is-style-fill hide-dark-mode has-transform" style="padding-top:6px;padding-right:6px;padding-bottom:6px;padding-left:var(--wp--preset--spacing--lg);--filter-hover:brightness(110%);--transform-icon-hover:rotate(45deg)"><a class="wp-block-button__link has-primary-400-color has-neutral-950-background-color has-text-color has-background has-link-color wp-element-button" style="padding-top:6px;padding-right:6px;padding-bottom:6px;padding-left:var(--wp--preset--spacing--lg)"><mark style="background-color:rgba(0, 0, 0, 0)" class="has-inline-color has-neutral-0-color">Contact us</mark><img role="presentation" style="-webkit-mask-image:url(data:image/svg+xml;utf8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%2048%2048%22%3E%0A%09%3Cpath%20fill%3D%22currentcolor%22%0A%09%09%20%20d%3D%22M24%200C10.75%200%200%2010.75%200%2024s10.75%2024%2024%2024%2024-10.75%2024-24S37.25%200%2024%200Zm7%2018v9.75c0%20.55-.45%201-1%201s-1-.45-1-1v-7.34L18.71%2030.7c-.2.2-.45.29-.71.29s-.51-.1-.71-.29a.996.996%200%200%201%200-1.41L27.58%2019h-7.34c-.55%200-1-.45-1-1s.45-1%201-1h9.75c.13%200%20.26.03.38.08a1.004%201.004%200%200%201%20.55.55c.05.12.07.24.08.38Z%22%2F%3E%0A%3C%2Fsvg%3E%0A); --width:54px; --width-desktop:54px;" alt="" src="" class="has-inline-svg"></a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons -->
<!-- wp:group {"style":{"spacing":{"blockGap":{"left":"var:preset|spacing|xxs"}}},"layout":{"type":"flex","flexWrap":"nowrap","justifyContent":"left","verticalAlignment":"center"}} -->
<div class="wp-block-group"><!-- wp:group {"style":{"position":{"all":"relative"}},"className":"is-style-light","layout":{"type":"flex","orientation":"vertical"}} -->
<div class="wp-block-group is-style-light"><!-- wp:image {"style":{"elements":{"link":{"color":{"text":"var:preset|color|primary-200"}}},"spacing":{"margin":{"top":"0","bottom":"0","left":"0","right":"0"}}},"className":"is-style-icon","animation":{"name":"fade-out-pop","duration":"2","event":"infinite","iterationCount":"1","delay":"0.5"},"textColor":"primary-200","iconSet":"wordpress","iconName":"circle-filled","iconSize":"30px","iconSvgString":"\u003csvg xmlns=\u0022http://www.w3.org/2000/svg\u0022 xml:space=\u0022preserve\u0022 viewBox=\u00220 0 2000 2000\u0022 role=\u0022img\u0022 aria-labelledby=\u0022icon-6619fc77b9623\u0022 data-icon=\u0022wordpress-circle-filled\u0022 width=\u002224\u0022 height=\u002224\u0022 fill=\u0022currentColor\u0022\u003e\u003ctitle id=\u0022icon-6619fc77b9623\u0022\u003eCircle Filled Icon\u003c/title\u003e\u003ccircle cx=\u00221000\u0022 cy=\u00221000\u0022 r=\u0022750\u0022\u003e\u003c/circle\u003e\u003c/svg\u003e"} -->
<figure class="wp-block-image is-style-icon has-primary-200-color has-text-color has-link-color has-animation" style="margin-top:0;margin-right:0;margin-bottom:0;margin-left:0;--animation-event:infinite;animation-iteration-count:infinite;animation-name:fade-out-pop;animation-duration:2s;animation-delay:0.5s;--wp--custom--icon--color:var(--wp--preset--color--primary-200,currentColor);--wp--custom--icon--margin:0 0 0 0;--wp--custom--icon--size:30px;--wp--custom--icon--url:url('data:image/svg+xml;utf8,<svg xmlns=&quot;http://www.w3.org/2000/svg&quot; xml:space=&quot;preserve&quot; viewBox=&quot;0 0 2000 2000&quot; role=&quot;img&quot; aria-labelledby=&quot;icon-6619fc77b9623&quot; data-icon=&quot;wordpress-circle-filled&quot; width=&quot;24&quot; height=&quot;24&quot; fill=&quot;currentColor&quot;&gt;<title id=&quot;icon-6619fc77b9623&quot;&gt;Circle Filled Icon</title&gt;<circle cx=&quot;1000&quot; cy=&quot;1000&quot; r=&quot;750&quot;&gt;</circle&gt;</svg&gt;')"><img alt=""/></figure>
<!-- /wp:image -->
<!-- wp:image {"style":{"elements":{"link":{"color":{"text":"var:preset|color|primary-400"}}},"position":{"all":"absolute"},"spacing":{"margin":{"top":"0","bottom":"0","left":"0","right":"0"}},"top":{"all":"0px","desktop":"0px"},"right":{"all":"0px","desktop":"0px"},"bottom":{"all":"0px","desktop":"0px"},"left":{"all":"0px","desktop":"0px"},"height":{"all":"12px"}},"className":"is-style-icon margin-auto","animation":{"name":"pulse","duration":"2","event":"infinite","iterationCount":"1","delay":"0"},"textColor":"primary-400","iconSet":"wordpress","iconName":"circle-filled","iconSize":"12px","iconSvgString":"\u003csvg xmlns=\u0022http://www.w3.org/2000/svg\u0022 xml:space=\u0022preserve\u0022 viewBox=\u00220 0 2000 2000\u0022 role=\u0022img\u0022 aria-labelledby=\u0022icon-6619fc77b9623\u0022 data-icon=\u0022wordpress-circle-filled\u0022 width=\u002224\u0022 height=\u002224\u0022 fill=\u0022currentColor\u0022\u003e\u003ctitle id=\u0022icon-6619fc77b9623\u0022\u003eCircle Filled Icon\u003c/title\u003e\u003ccircle cx=\u00221000\u0022 cy=\u00221000\u0022 r=\u0022750\u0022\u003e\u003c/circle\u003e\u003c/svg\u003e"} -->
<figure class="wp-block-image is-style-icon margin-auto has-primary-400-color has-text-color has-link-color has-animation" style="margin-top:0;margin-right:0;margin-bottom:0;margin-left:0;--animation-event:infinite;animation-iteration-count:infinite;animation-name:pulse;animation-duration:2s;animation-delay:0s;--wp--custom--icon--color:var(--wp--preset--color--primary-400,currentColor);--wp--custom--icon--margin:0 0 0 0;--wp--custom--icon--size:12px;--wp--custom--icon--url:url('data:image/svg+xml;utf8,<svg xmlns=&quot;http://www.w3.org/2000/svg&quot; xml:space=&quot;preserve&quot; viewBox=&quot;0 0 2000 2000&quot; role=&quot;img&quot; aria-labelledby=&quot;icon-6619fc77b9623&quot; data-icon=&quot;wordpress-circle-filled&quot; width=&quot;24&quot; height=&quot;24&quot; fill=&quot;currentColor&quot;&gt;<title id=&quot;icon-6619fc77b9623&quot;&gt;Circle Filled Icon</title&gt;<circle cx=&quot;1000&quot; cy=&quot;1000&quot; r=&quot;750&quot;&gt;</circle&gt;</svg&gt;')"><img alt=""/></figure>
<!-- /wp:image --></div>
<!-- /wp:group -->
<!-- wp:paragraph {"style":{"typography":{"fontStyle":"normal","fontWeight":"600"}},"className":"nowrap","fontSize":"14"} -->
<p class="nowrap has-14-font-size" style="font-style:normal;font-weight:600">Available now</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->
<!-- wp:column {"width":"60%"} -->
<div class="wp-block-column" style="flex-basis:60%"><!-- wp:group {"style":{"spacing":{"padding":{"top":"0","bottom":"0"}}},"layout":{"type":"default"}} -->
<div class="wp-block-group" style="padding-top:0;padding-bottom:0"><!-- wp:details {"style":{"spacing":{"padding":{"top":"28px","bottom":"28px","left":"28px","right":"28px"},"margin":{"top":"var:preset|spacing|sm","bottom":"0"}},"border":{"radius":"20px"},"elements":{"link":{"color":{"text":"var:preset|color|neutral-950"}}}},"backgroundColor":"neutral-50","textColor":"neutral-950","className":"is-style-summary-heading","fontSize":"22","expandIcon":"circle"} -->
<details class="wp-block-details is-style-summary-heading has-neutral-950-color has-neutral-50-background-color has-text-color has-background has-link-color has-22-font-size" style="border-radius:20px;margin-top:var(--wp--preset--spacing--sm);margin-bottom:0;padding-top:28px;padding-right:28px;padding-bottom:28px;padding-left:28px"><summary>Do themes require any plugins?</summary><!-- wp:paragraph {"placeholder":"Type / to add a hidden block"} -->
<p>No, there are no plugins required by this theme. Everything you need to design an amazing website is provided by the free Blockify parent theme. You can optionally add the Blockify Pro plugin for extra functionality and features.</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->
<!-- wp:details {"style":{"spacing":{"padding":{"top":"28px","bottom":"28px","left":"28px","right":"28px"},"margin":{"top":"var:preset|spacing|sm","bottom":"0"}},"border":{"radius":"20px"},"elements":{"link":{"color":{"text":"var:preset|color|neutral-950"}}}},"backgroundColor":"neutral-50","textColor":"neutral-950","className":"is-style-summary-heading","fontSize":"22","expandIcon":"circle"} -->
<details class="wp-block-details is-style-summary-heading has-neutral-950-color has-neutral-50-background-color has-text-color has-background has-link-color has-22-font-size" style="border-radius:20px;margin-top:var(--wp--preset--spacing--sm);margin-bottom:0;padding-top:28px;padding-right:28px;padding-bottom:28px;padding-left:28px"><summary>Does this theme support WooCommerce and EDD?</summary><!-- wp:paragraph {"placeholder":"Type / to add a hidden block"} -->
<p>Yes, Blockify themes are compatible with the WooCommerce and also Easy Digital Downloads plugins for creating an eCommerce store.</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->
<!-- wp:details {"style":{"spacing":{"padding":{"top":"28px","bottom":"28px","left":"28px","right":"28px"},"margin":{"top":"var:preset|spacing|sm","bottom":"0"}},"border":{"radius":"20px"},"elements":{"link":{"color":{"text":"var:preset|color|neutral-950"}}}},"backgroundColor":"neutral-50","textColor":"neutral-950","className":"is-style-summary-heading","fontSize":"22","expandIcon":"circle"} -->
<details class="wp-block-details is-style-summary-heading has-neutral-950-color has-neutral-50-background-color has-text-color has-background has-link-color has-22-font-size" style="border-radius:20px;margin-top:var(--wp--preset--spacing--sm);margin-bottom:0;padding-top:28px;padding-right:28px;padding-bottom:28px;padding-left:28px"><summary>Does this theme work with Elementor or page builders?</summary><!-- wp:paragraph {"placeholder":"Type / to add a hidden block"} -->
<p>Yes, you can use Elementor or your page builder of choice with any of our themes. Blockify provides a Full Width page template which is perfect for creating full-width pages between the site header and footer. There is also a Blank page template which can be used to create complete pages, including header and footer, with your page builder.</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph -->
<p>Please note that blocks cannot be edited with page builders. Blocks can be customized with the WordPress block editor. Page builders can be used to replace parts of your site, however they can't be used to edit blocks.</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->
<!-- wp:details {"style":{"spacing":{"padding":{"top":"28px","bottom":"28px","left":"28px","right":"28px"},"margin":{"top":"var:preset|spacing|sm","bottom":"0"}},"border":{"radius":"20px"},"elements":{"link":{"color":{"text":"var:preset|color|neutral-950"}}}},"backgroundColor":"neutral-50","textColor":"neutral-950","className":"is-style-summary-heading","fontSize":"22","expandIcon":"circle"} -->
<details class="wp-block-details is-style-summary-heading has-neutral-950-color has-neutral-50-background-color has-text-color has-background has-link-color has-22-font-size" style="border-radius:20px;margin-top:var(--wp--preset--spacing--sm);margin-bottom:0;padding-top:28px;padding-right:28px;padding-bottom:28px;padding-left:28px"><summary>How to change the site logo?</summary><!-- wp:paragraph {"placeholder":"Type / to add a hidden block"} -->
<p>Head to the Site Editor and then navigate to the Header Template Part. From there, click on the existing logo and then replace it with a block of your choice. You can use an Image block, SVG, Site Logo or Site Title block as the site logo, the choice is yours. We prefer to use SVGs for logos because they scale perfectly at all screen sizes and also support variable colors which makes them ideal for use with dark mode and animations.</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->
<!-- wp:details {"style":{"spacing":{"padding":{"top":"28px","bottom":"28px","left":"28px","right":"28px"},"margin":{"top":"var:preset|spacing|sm","bottom":"0"}},"border":{"radius":"20px"},"elements":{"link":{"color":{"text":"var:preset|color|neutral-950"}}}},"backgroundColor":"neutral-50","textColor":"neutral-950","className":"is-style-summary-heading","fontSize":"22","expandIcon":"circle"} -->
<details class="wp-block-details is-style-summary-heading has-neutral-950-color has-neutral-50-background-color has-text-color has-background has-link-color has-22-font-size" style="border-radius:20px;margin-top:var(--wp--preset--spacing--sm);margin-bottom:0;padding-top:28px;padding-right:28px;padding-bottom:28px;padding-left:28px"><summary>How do I add custom SVG images?</summary><!-- wp:paragraph {"placeholder":"Type / to add a hidden block"} -->
<p>Custom SVG images can be added to your site in multiple ways. The first option is to use the core Image block, however this requires the use of the Safe SVG plugin since WordPress doesn't allow SVG uploads by default. There is also an SVG block variation provided with this theme which lets you simply paste SVG HTML code into an Image block. The third option is to use the Icon block variation. This displays an SVG icon which you can choose from a library of included icons, or upload your own.</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->
<!-- wp:details {"style":{"spacing":{"padding":{"top":"28px","bottom":"28px","left":"28px","right":"28px"},"margin":{"top":"var:preset|spacing|sm","bottom":"0"}},"border":{"radius":"20px"},"elements":{"link":{"color":{"text":"var:preset|color|neutral-950"}}}},"backgroundColor":"neutral-50","textColor":"neutral-950","className":"is-style-summary-heading","fontSize":"22","expandIcon":"circle"} -->
<details class="wp-block-details is-style-summary-heading has-neutral-950-color has-neutral-50-background-color has-text-color has-background has-link-color has-22-font-size" style="border-radius:20px;margin-top:var(--wp--preset--spacing--sm);margin-bottom:0;padding-top:28px;padding-right:28px;padding-bottom:28px;padding-left:28px"><summary>How can I add animations to blocks?</summary><!-- wp:paragraph {"placeholder":"Type / to add a hidden block"} -->
<p>Most core blocks have animation supported added. You can add and change transition effects without needing any code.</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->
<!-- wp:details {"style":{"spacing":{"padding":{"top":"28px","bottom":"28px","left":"28px","right":"28px"},"margin":{"top":"var:preset|spacing|sm","bottom":"0"}},"border":{"radius":"20px"},"elements":{"link":{"color":{"text":"var:preset|color|neutral-950"}}}},"backgroundColor":"neutral-50","textColor":"neutral-950","className":"is-style-summary-heading","fontSize":"22","expandIcon":"circle"} -->
<details class="wp-block-details is-style-summary-heading has-neutral-950-color has-neutral-50-background-color has-text-color has-background has-link-color has-22-font-size" style="border-radius:20px;margin-top:var(--wp--preset--spacing--sm);margin-bottom:0;padding-top:28px;padding-right:28px;padding-bottom:28px;padding-left:28px"><summary>What version of PHP and WordPress is needed?</summary><!-- wp:paragraph {"placeholder":"Type / to add a hidden block"} -->
<p>PHP 7.4 or higher is required however we recommend using a later version PHP 8.2 or above. All themes are tested with the latest version of WordPress.</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->
<!-- wp:details {"style":{"spacing":{"padding":{"top":"28px","bottom":"28px","left":"28px","right":"28px"},"margin":{"top":"var:preset|spacing|sm","bottom":"0"}},"border":{"radius":"20px"},"elements":{"link":{"color":{"text":"var:preset|color|neutral-950"}}}},"backgroundColor":"neutral-50","textColor":"neutral-950","className":"is-style-summary-heading","fontSize":"22","expandIcon":"circle"} -->
<details class="wp-block-details is-style-summary-heading has-neutral-950-color has-neutral-50-background-color has-text-color has-background has-link-color has-22-font-size" style="border-radius:20px;margin-top:var(--wp--preset--spacing--sm);margin-bottom:0;padding-top:28px;padding-right:28px;padding-bottom:28px;padding-left:28px"><summary>How can I display blog posts on the home page?</summary><!-- wp:paragraph {"placeholder":"Type / to add a hidden block"} -->
<p>This theme comes with multiple blog patterns that can be used to display posts on any page. Simply add a blog pattern to your home page template, or the page that is set as the Front Page. You can customize the Query Loop to suit your needs. Front page settings can be found from the WordPress admin dashboard under Settings → Reading.</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->
<!-- wp:details {"style":{"spacing":{"padding":{"top":"28px","bottom":"28px","left":"28px","right":"28px"},"margin":{"top":"var:preset|spacing|sm","bottom":"0"}},"border":{"radius":"20px"},"elements":{"link":{"color":{"text":"var:preset|color|neutral-950"}}}},"backgroundColor":"neutral-50","textColor":"neutral-950","className":"is-style-summary-heading","fontSize":"22","expandIcon":"circle"} -->
<details class="wp-block-details is-style-summary-heading has-neutral-950-color has-neutral-50-background-color has-text-color has-background has-link-color has-22-font-size" style="border-radius:20px;margin-top:var(--wp--preset--spacing--sm);margin-bottom:0;padding-top:28px;padding-right:28px;padding-bottom:28px;padding-left:28px"><summary>How do I create a child theme?</summary><!-- wp:paragraph {"placeholder":"Type / to add a hidden block"} -->
<p>We recommend using the create block theme plugin to create your own child themes. With a little know-how, they can be the perfect way to build your own website. They inherit all of the parent theme's design which saves you a tonne of work and provides a head start for your next project.</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details --></div>
<!-- /wp:group --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:group -->